### ISSUE TITLE
Permission to adopt this repo for submission to the Rack v2 library

### ISSUE THREAD

**Issue by SteveRussell33** [gbrandt1/southpole-vcvrack#57]
As per the post here: https://community.vcvrack.com/t/now-taking-submissions-of-v2-plugins-to-the-library/14747

I have been working on this fine collection of modules (inc. Parasites branch) on separate forked repo's - one each for Southpole/Southpole Parasites - to bring them up to date for the imminent release of VCV Rack 2 Free/Pro editions.

I am posting this issue to ask for permission to take over the maintenance, now and in the future, of this collection if you no longer wish to do so.
Please reply to this issue or email support@vcvrack.com approving transfer of maintainership, referencing this issue so that there is a record of the tranfer that can be added to the plugin issue entry in the v2 library.

Thanks in advance
Steve

**Comment by gbrandt1** [comment]
Hello Steve,

Thanks for your interest.

As you have well understood I have not been able to follow changes 
to the API and governance in VCVRack of the past year. As this is unlikely
to change in the near future I am indeed not opposed to be no longer a 
roadblock in reincluding the southpole modules back into VCVRack 2.

However I would like to understand the implications of "handing over" maintainership
a bit better before agreeing. Is it not possible to add a maintainer, like in other open 
source projects, rather than handing over completely?
Can we talk about this by email perhaps? Please contact me at gbrandt@cern.ch.

Cheers
southpole
(Gerhard Brandt)

**Comment by mjsyts** [comment]
Please keep us posted on this. There are a number of modules you've developed that would be fantastic to have back in the library. Thanks for all of your hard work on developing the originals - they're excellent tools.

**Comment by SteveRussell33** [comment]
Current situation: https://community.vcvrack.com/t/plugins-that-are-questionable-whether-there-will-be-v2-updates/14364/185

**Comment by gbrandt1** [comment]
hi guys, Steve, i'm not ignoring you. it is correct that the end of the year is always the busiest period where everything piles up. i'll have a look at this over the break. i need to think a bit about the governance and the two-tier system of free/paid VCVRack 2.
cheers

**Comment by ph1-xyz** [comment]
Are there updates on this?

Can the Riemannian generator be compiled for Rack 2?


Thanks!

**Comment by SteveRussell33** [comment]
No there will be no updates for these modules in the near future.
